[package]
name = "sdl_ttf"
version = "0.1.0"
authors = ["Daogang Tang <daogangtang@gmail.com>"]
edition = "2018"

[lib]
name = "sdl_ttf"
path = "lib.rs"

[dependencies]
libc = "^0.2.137"

[dependencies.sdl]
path = "../.."

[dev-dependencies]
sdl_image = {path="../sdl_image"}
